apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        role: green
    spec:
      containers:
      - name: flask-container
        image: localhost:8080/flask-app:2.0
        ports:
        - containerPort: 5000